# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Vim Bindings
set -o vi

# Golang pathing
export GOPATH=~/devel/go
export GOROOT=/usr/local/opt/go/libexec
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$GOROOT/bin

# CLI Shortcuts
alias ee="exit"
alias ll='ls -lah'

# Git Shortcuts
alias gts='git status'
alias gta='git add' 
alias gtc='git commit'
alias gtd='git diff'
alias gtrm='git rm'
alias gtsubup='git submodule update --init --recursive'

# Vagrant Shortcuts
alias vgs='vagrant status'
alias vgu='vagrant up'
alias vgh='vagrant halt'
alias vgd='vagrant destroy'
alias vgs='vagrant suspend'

# Preprocessor Shortcuts
alias lc='lessc'

# Customize Bash Prompt
PS1='\w \$ '

# Bash Functions
lsfilesize() {
    bash ~/workflow/bin/lsize.sh $1 $2
}

# Load private configs
if [ -f ~/.bashrc_private ]; then
    source ~/.bashrc_private
fi
