# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# CLI Shortcuts
alias ee="exit"
alias ll='ls -lah'

# Git Shortcuts
alias gts='git status'
alias gta='git add' 
alias gtc='git commit'
alias gtd='git diff'
alias gtrm='git rm'

# Load private configs
if [ -f ~/.bashrc_private ]; then
    source ~/.bashrc_private
fi
